version: '3.8'
services:
  localstack:
    image: localstack/localstack:latest
    ports:
      - "4566-4597:4566-4597"
      - "${PORT_WEB_UI-8010}:${PORT_WEB_UI-8010}"
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
      - SERVICES=dynamodb:4566,kinesis:4567
      - DEFAULT_REGION=ap-southeast-1
      - PORT_WEB_UI=8010
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./volume:/tmp/localstack"

  aws-cli:
    image: amazon/aws-cli:latest
    depends_on:
      - localstack
    environment:
      AWS_DEFAULT_PROFILE: dynamodb-local
      AWS_ENDPOINT: --endpoint-url=http://localstack:4566
    entrypoint: /bin/sh -c
    volumes:
      - './init-scripts:/init-scripts'
    command: >
      '
       for script_name in /init-scripts/*.sh; do
         sh $$script_name
       done
      '

  dynamodb-admin:
    depends_on:
      - localstack
    image: aaronshaf/dynamodb-admin
    ports:
      - "8001:8001"
    environment:
      - DYNAMO_ENDPOINT=http://localstack:4566
      - AWS_REGION=ap-southeast-1